### ISSUE TITLE
Deploy to Bluemix broken

### ISSUE THREAD

**Issue by sirhc-k** [ibm-cds-labs/metrics-collector#10]
The deploy to Bluemix button is broken.  

Screenshot of error -

>![image](https://cloud.githubusercontent.com/assets/5659625/15329433/bd4162a6-1c26-11e6-940f-ce91c03dd0f1.png)

Screenshot of deployment log -

>
![image](https://cloud.githubusercontent.com/assets/5659625/15329529/0988bff6-1c27-11e6-940c-c9ef41399bcc.png)

**Comment by rajrsingh** [comment]
I'm looking at it.

**Comment by rajrsingh** [comment]
@sirhc-k please try again. I fixed manifest.yml which had accidentally had some lines deleted.

**Comment by sirhc-k** [comment]
@rajrsingh 

seems to be working again; thanks!
