### ISSUE TITLE
Click Tracking

### ISSUE THREAD

**Issue by bradley-holt** [ibm-cds-labs/metrics-collector#7]
Is it possible to use the Metrics Collector for click tracking? The specific use case in question is tracking a click on a link which downloads a file (in which case there is no page load to initiate tracking, thus the need for click tracking). With Google Analytics, you can listen for the `click` event on a hyperlink and then fire off a tracking event in JavaScript. I have labeled this issue as a "question." If it turns out that this is not currently possible, then I will update the label to "enhancement."

**Comment by DTAIEB** [comment]
Metrics Collector is generically tracking element with tag 'a' and 'area'. So I expect the click tracking to work if the download is implemented with <a> or <area>
e.g. <a href="http://myfile.zip" download>Download</a>
I believe that for any other download implementation, you would have to create your own tracker plugin

**Comment by bradley-holt** [comment]
@DTAIEB I talked with @rajrsingh earlier and he indicated that we are not currently tracking download links in dW. For example, we have no tracking data for the download link at the bottom of this article:
https://developer.ibm.com/clouddataservices/2016/01/25/start-developing-ios-apps-swift-with-cloud-sync-part-1-the-datastore/

Might this just be an integration issue?

**Comment by bradley-holt** [comment]
Closing this issue as this capability is, in fact, part of the Metrics Collector.
